The Nathaniel Derby Pickman Foundation, aided by a few special contributions, financed the expedition; hence our preparations were extremely thorough, despite the absence of great publicity. The dogs, sledges, machines, camp materials, and unassembled parts of our five planes were delivered in Boston, and there our ships were loaded. We were marvelously well-equipped for our specific purposes, and in all matters pertaining to supplies, regimen, transportation, and camp construction we profited by the excellent example of our many recent and exceptionally brilliant predecessors. It was the unusual number and fame of these predecessors which made our own expedition—ample though it was—so little noticed by the world at large.

As the newspapers told, we sailed from Boston Harbor on September 2nd, 1930, taking a leisurely course down the coast and through the Panama Canal, and stopping at Samoa and Hobart, Tasmania, at which latter place we took on final supplies. None of our exploring party had ever been in the polar regions before, hence we all relied greatly on our ship captains—J. B. Douglas, commanding the brig Arkham, and serving as commander of the sea party, and Georg Thorfinnssen, commanding the barque Miskatonic—both veteran whalers in antarctic waters.

As we left the inhabited world behind, the sun sank lower and lower in the north, and stayed longer and longer above the horizon each day. At about 62° South Latitude we sighted our first icebergs—table-like objects with vertical sides—and just before reaching the antarctic circle, which we crossed on October 20th with appropriately quaint ceremonies, we were considerably troubled with field ice. The falling temperature bothered me considerably after our long voyage through the tropics, but I tried to brace up for the worse rigors to come. On many occasions the curious atmospheric effects enchanted me vastly; these including a strikingly vivid mirage—the first I had ever seen—in which distant bergs became the battlements of unimaginable cosmic castles.

Pushing through the ice, which was fortunately neither extensive nor thickly packed, we regained open water at South Latitude 67°, East Longitude 175° On the morning of October 26th a strong land blink appeared on the south, and before noon we all felt a thrill of excitement at beholding a vast, lofty, and snow-clad mountain chain which opened out and covered the whole vista ahead. At last we had encountered an outpost of the great unknown continent and its cryptic world of frozen death. These peaks were obviously the Admiralty Range discovered by Ross, and it would now be our task to round Cape Adare and sail down the east coast of Victoria Land to our contemplated base on the shore of McMurdo Sound, at the foot of the volcano Erebus in South Latitude 77° 9'.

The last lap of the voyage was vivid and fancy-stirring. Great barren peaks of mystery loomed up constantly against the west as the low northern sun of noon or the still lower horizon-grazing southern sun of midnight poured its hazy reddish rays over the white snow, bluish ice and water lanes, and black bits of exposed granite slope. Through the desolate summits swept raging, intermittent gusts of the terrible antarctic wind; whose cadences sometimes held vague suggestions of a wild and half-sentient musical piping, with notes extending over a wide range, and which for some subconscious mnemonic reason seemed to me disquieting and even dimly terrible. Something about the scene reminded me of the strange and disturbing Asian paintings of Nicholas Roerich, and of the still stranger and more disturbing descriptions of the evilly fabled plateau of Leng which occur in the dreaded Necronomicon of the mad Arab Abdul Alhazred. I was rather sorry, later on, that I had ever looked into that monstrous book at the college library.

On the 7th of November, sight of the westward range having been temporarily lost, we passed Franklin Island; and the next day descried the cones of Mts. Erebus and Terror on Ross Island ahead, with the long line of the Parry Mountains beyond. There now stretched off to the east the low, white line of the great ice barrier, rising perpendicularly to a height of two hundred feet like the rocky cliffs of Quebec, and marking the end of southward navigation. In the afternoon we entered McMurdo Sound and stood off the coast in the lee of smoking Mt. Erebus. The scoriac peak towered up some twelve thousand, seven hundred feet against the eastern sky, like a Japanese print of the sacred Fujiyama, while beyond it rose the white, ghostlike height of Mt. Terror, ten thousand, nine hundred feet in altitude, and now extinct as a volcano.

Puffs of smoke from Erebus came intermittently, and one of the graduate assistants—a brilliant young fellow named Danforth—pointed out what looked like lava on the snowy slope, remarking that this mountain, discovered in 1840, had undoubtedly been the source of Poe's image when he wrote seven years later:

"—the lavas that restlessly roll
Their sulphurous currents down Yaanek
In the ultimate climes of the pole—
That groan as they roll down Mount Yaanek
In the realms of the boreal pole."

Danforth was a great reader of bizarre material, and had talked a good deal of Poe. I was interested myself because of the antarctic scene of Poe's only long story—the disturbing and enigmatical Arthur Gordon Pym. On the barren shore, and on the lofty ice barrier in the background, myriads of grotesque penguins squawked and flapped their fins, while many fat seals were visible on the water, swimming or sprawling across large cakes of slowly drifting ice.

Using small boats, we effected a difficult landing on Ross Island shortly after midnight on the morning of the 9th, carrying a line of cable from each of the ships and preparing to unload supplies by means of a breeches-buoy arrangement. Our sensations on first treading Antarctic soil were poignant and complex, even though at this particular point the Scott and Shackleton expeditions had preceded us. Our camp on the frozen shore below the volcano's slope was only a provisional one, headquarters being kept aboard the Arkham. We landed all our drilling apparatus, dogs, sledges, tents, provisions, gasoline tanks, experimental ice-melting outfit, cameras, both ordinary and aerial, aeroplane parts, and other accessories, including three small portable wireless outfits—besides those in the planes—capable of communicating with the Arkham's large outfit from any part of the antarctic continent that we would be likely to visit. The ship's outfit, communicating with the outside world, was to convey press reports to the Arkham Advertiser's powerful wireless station on Kingsport Head, Massachusetts. We hoped to complete our work during a single antarctic summer; but if this proved impossible, we would winter on the Arkham, sending the Miskatonic north before the freezing of the ice for another summer's supplies.
